---
- name: include platform specific tasks & variables.
  include: "{{ ansible_distribution }}/main.yml"

- name: Install required software (unzip, ipset etc.)
  become: yes
  become_method: sudo
  package: name={{item}} state=latest
  with_items:
  - ipset
  - unzip
  - curl

- name: Create temporary DCOS dirctory
  file: path="{{dcos_temp_dir}}" state=directory

- name: Download DCOS installer
  get_url: url={{bootstrap_url}} dest={{dcos_temp_dir}}/{{bootstrap_script}}

- name: Make {{bootstrap_script}} executable
  file: path={{dcos_temp_dir}}/{{bootstrap_script}} state=touch mode=0700

- name: Run the DCOS installer for masters
  become: yes
  become_method: sudo
  command: bash {{dcos_temp_dir}}/{{bootstrap_script}} master
  when: groups['tag_dcos_master'] is defined and inventory_hostname in groups['tag_dcos_master']

- name: Run the DCOS installer for slaves
  become: yes
  become_method: sudo
  command: bash {{dcos_temp_dir}}/{{bootstrap_script}} slave
  when: groups['tag_dcos_slave'] is defined and inventory_hostname in groups['tag_dcos_slave']

- name: Run the DCOS installer for public slaves
  become: yes
  become_method: sudo
  command: bash {{dcos_temp_dir}}/{{bootstrap_script}} slave_public
  when: groups['tag_dcos_slave_public'] is defined and inventory_hostname in groups['tag_dcos_slave_public']

